import winreg

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
WINDOW_MARGIN = 20
LAYOUT_SPACING = 15

REG_FILE_HEADER = "Windows Registry Editor Version 5.00"
REG_FILE_ENCODINGS = ['utf-16', 'utf-8']

STATUS_MATCH = "✅"
STATUS_DIFFERENT_FILE = "📄"
STATUS_DIFFERENT_SYSTEM = "🖥️"
STATUS_NOT_FOUND = "❌"
STATUS_ERROR = "⚠️"

REGISTRY_ROOT_KEYS = {
    "HKEY_LOCAL_MACHINE": winreg.HKEY_LOCAL_MACHINE,
    "HKEY_CURRENT_USER": winreg.HKEY_CURRENT_USER,
    "HKEY_CLASSES_ROOT": winreg.HKEY_CLASSES_ROOT,
    "HKEY_USERS": winreg.HKEY_USERS,
    "HKEY_CURRENT_CONFIG": winreg.HKEY_CURRENT_CONFIG,
}

APP_TITLE = "ScriptForge"
APP_CREDITS = "Credits: yuuki_0711"
